
occupancy_map_path: /home/user1/UC3/src/components/planner_component/resource/occupancy_maps_madama3_doors_16_experiments/occupancy_map_madama3_doors_16_experiments_5_levels.yaml
cliff_map_path: /home/user1/UC3/src/components/planner_component/resource/MoDs/map_madama3_september.csv
time_bound_lrtdp: 500
time_bound_real: 50
convergence_threshold: 0.1
wait_time: 20
explain_time: 20
bt_file_path: /home/user1/UC3/src/behavior_tree/BT/bt_scheduler.xml
detections_topic: static_tracks